### ISSUE TITLE
Clarify AuthenticationData usage

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#132]
In the User-Interactive Authentication API, the `AuthenticationData` currently is defined as 

```rust
pub struct AuthenticationData {
    /// The login type that the client is attempting to complete.
    #[serde(rename = "type")]
    pub kind: String,
    /// The value of the session key given by the homeserver.
    pub session: Option<String>,
}
```

A few things should be added:
- Make a comment for server implementors that if `session` is `None`, then the entire authentication data can be ignored. (Perhaps we could modify the types or `De-/Serialize` impls to make this state unrepresentable for a client?)
- Authentication parameters are supposed appear in this object after the initial stage. E.g., `example_credential` in the following object:
  ```json
  {
    "a_request_parameter": "something",
    "another_request_parameter": "something else",
    "auth": {
        "type": "example.type.foo",
        "session": "xxxxxx",
        "example_credential": "verypoorsharedsecret"
    }
  }
  ```
  However, this struct doesn't have a place to put those parameters.

**Comment by jplatte** [comment]
> if session is `None`, then the entire authentication data can be ignored

I don't think we should do anything concerning this. The spec says the `type` field is required, so we won't make it optional (unless the spec is changed). Also we don't provide nearly enough documentation for people to be able to implement a homeserver based on our docs alone, so I don't think increasing the doc scope for this one case is that useful. That's not to say I would reject PRs making the docs more detailed though.

> Authentication parameters are supposed appear in this object after the initial stage. [...]

We should fix this. I've labeled the issue as bug because as-is, the struct is kind of unusable. Let's add a `Map<String, serde_json::Value>` with `#[serde(flatten)]` at the end of it.

**Comment by iinuwa** [comment]
Will do.

Should we also add a type for the UIAA 401 responses? E.g.:

```json
{
  "flows": [
    {
      "stages": [ "example.type.foo", "example.type.bar" ]
    },
    {
      "stages": [ "example.type.foo", "example.type.baz" ]
    }
  ],
  "params": {
      "example.type.baz": {
          "example_key": "foobar"
      }
  },
  "session": "xxxxxx"
}
```

**Comment by iinuwa** [comment]
And is that meant to be a `serde_json::Map`, or a `HashMap` like we use elsewhere?

**Comment by iinuwa** [comment]
All right, just pushed again using BTreeMap. I think that's all I can do for today; let me know if you want anything else changed!

**Comment by iinuwa** [comment]
I think this is covered by #133. Closing
