### ISSUE TITLE
Add send-to-device endpoint.

### ISSUE THREAD

**Issue by iinuwa** [ruma/ruma-client-api#70]
The send-to-device endpoint is missing: [PUT /_matrix/client/r0/sendToDevice/{eventType}/{txnId}](https://matrix.org/docs/spec/client_server/r0.6.0#put-matrix-client-r0-sendtodevice-eventtype-txnid).

See the link to the Matrix spec for more details.

**Comment by jplatte** [comment]
This one has one small gotcha in that one of the types involved is "DeviceID or `*`". We might either just use `String` as the type for that for now, or create a separate type for that. (either in ruma-identifiers, if this kind of usage is more broadly useful than just this one endpoint, or in the new module otherwise)

**Comment by iinuwa** [comment]
I think having a type for this would be good. The only other endpoint that has a similar behavior is [/keys/query](https://matrix.org/docs/spec/client_server/r0.6.0#post-matrix-client-r0-keys-query), which even then is not exactly the same (an empty list represents all devices there, while a `*` represents all devices here.) Because of that, I think it would make sense to add it to the module rather than ruma-identifiers.

Should the new type follow the same de-/serialization style of `RoomIdOrAlias`?

**Comment by jplatte** [comment]
Sure, sounds good!

**Comment by iinuwa** [comment]
Closed by #107
